#!/usr/bin/env python3
import os
import os.path
import requests
def download(url):
    req = requests.get(url)
    if req.status_dode == 404:
        print('no such file found %s' % url)
        return
        
